# Generated by Django 3.1.3 on 2020-11-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
